---
apiVersion: v1
kind: Service
metadata:
  name: lbp
  namespace: default
  labels:
    name: lbp
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8080
  selector:
    name: lbp-server 
---
